[profile.default]
src = "contracts"
test = 'foundry/tests'
out = "artifacts"
libs = ["node_modules", "foundry/lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]
optimizer = true
optimizer-runs = 200
bytecode_hash = "none"
evm_version = "london"
extra_output_files = [
    "metadata"
]
ffi = true

[fmt]
line_length = 120
tab_width = 4

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
