[profile.default]
src = "contracts"
test = 'foundry/tests'
out = "artifacts"
libs = ["foundry/lib"]
optimizer = true
optimizer-runs = 200
extra_output_files = [
    "metadata"
]
ffi = true

[fmt]
line_length = 120
tab_width = 4

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
